(define (armarMatriz m n) (cortarCada (armarVector (* m n)) m n))
(define (armarVector m) (if (eq? m 0) '()
                            (append (armarVector (- m 1)) (list m))))
(define (cortarCada v m n) (if (eq? m 1) (list v)
                               (append (list (primeros n v)) (cortarCada (sacar n v) (- m 1) n))))
(define (primeros n v) (if (eq? n 1) (cons (car v) '())
                           (cons (car v) (primeros (- n 1) (cdr v)))))
(define (sacar n v) (if (eq? n 1) (cdr v)
                        (sacar (- n 1) (cdr v))))